### ISSUE TITLE
examples无法正常运行

### ISSUE THREAD

**Issue by recherst** [reactjs-ui/reactjs-pull-refresh#1]
package.json中用到的webpack和webpack-dev-server都太旧，下载后的demo无法正常运行，可否更新一下demo？

**Comment by hopefuture** [comment]
好，今天处理一下，谢谢反馈

**Comment by hopefuture** [comment]
已处理，升级到最新版本，例子中使用的是 json 模拟数据，实际你可以利用 ajax 或 fetch 从后端抓取数据，项目中使用完全没问题的，请放心使用
