### ISSUE TITLE
移动端站点

### ISSUE THREAD

**Issue by feelingwinds** [reactjs-ui/reactjs-pull-refresh#2]
做的移动端站点在安卓手机用浏览器打开正常，ios 系统打开后，只能显示跟屏幕一样的高度，再多的数据显示不出来，而且影响react-router 的后退，还有页面中数据点击后进入详情页要点好几次才能成功，这个我是我使用的问题还是什么问题呢

**Comment by hopefuture** [comment]
你可以使用 [react-alloytouch](https://github.com/reactjs-ui/react-alloytouch) 试试，抱歉

**Comment by hopefuture** [comment]
这个问题目前已解决，请更新最新版本试试，谢谢你的反馈
