### ISSUE TITLE
您好! 该插件有升级 react / react-dom 依赖到 @16.x 版本的计划吗?

### ISSUE THREAD

**Issue by Maple13** [reactjs-ui/reactjs-pull-refresh#8]
您好! 该插件有升级 react / react-dom 依赖到 @16.x 版本的计划吗?

**Comment by fallenleavesguy** [comment]
我看旧项目有人用了这个坑爹东西，太多地方用了，一时改不掉，又要升级到react 16，就基于某个没有大bug的渣渣版本改了可以在react 16下跑的版本[升级到16](https://github.com/dz-web/reactjs-pull-refresh)

不过，现在已经全部完成过渡了，已经彻底删除了这个东东。我换到这个了[rlist-view](https://github.com/gitpadtech/rlist-view)

**Comment by Maple13** [comment]
@yeluoqiuzhi 感谢，我也是接手之前同事的代码时遇到的问题，后来换了其他插件， 也感谢@hopefuture 的辛勤付出
